import { LineJoin } from "./pixi.mjs.js";
import { ZipAction } from "@benev/slate/x/watch/zip/action.js";
import type { ColorSource, TEXT_GRADIENT, TextStyleAlign, TextStyleFontStyle, TextStyleFontVariant, TextStyleFontWeight, TextStyleTextBaseline, TextStyleWhiteSpace } from "pixi.js";
import { Transition } from "./controllers/compositor/parts/transition-manager.js";
import { Filter, FilterType } from "./controllers/compositor/parts/filter-manager.js";
import { AnyEffect, AudioEffect, ExportStatus, Font, ImageEffect, TextEffect, EffectRect, VideoEffect, Standard, AspectRatio, State, HistoricalActionsWithBroadcast, NonHistoricalActionsWithBroadcast } from "./types.js";
import { Animation, AnimationFor } from "./controllers/compositor/parts/animation-manager.js";
export declare const non_historical: {
    clear_project: (state: import("./types.js").NonHistoricalState) => () => void;
    set_incoming_non_historical_state_webrtc: (state: import("./types.js").NonHistoricalState) => (historical: State) => void;
    set_standard: (state: import("./types.js").NonHistoricalState) => (standard: Standard) => void;
    set_aspect_ratio: (state: import("./types.js").NonHistoricalState) => (aspectRatio: AspectRatio) => void;
    set_bitrate: (state: import("./types.js").NonHistoricalState) => (value: number) => void;
    zoom_in: (state: import("./types.js").NonHistoricalState) => () => void;
    zoom_out: (state: import("./types.js").NonHistoricalState) => () => void;
    set_timecode: (state: import("./types.js").NonHistoricalState) => (timecode: number) => void;
    increase_timecode: (state: import("./types.js").NonHistoricalState) => (by_milliseconds: number) => void;
    set_is_playing: (state: import("./types.js").NonHistoricalState) => (is_playing: boolean) => void;
    toggle_is_playing: (state: import("./types.js").NonHistoricalState) => () => void;
    set_is_exporting: (state: import("./types.js").NonHistoricalState) => (is_exporting: boolean) => void;
    set_export_progress: (state: import("./types.js").NonHistoricalState) => (progress: number) => void;
    set_timebase: (state: import("./types.js").NonHistoricalState) => (timebase: number) => void;
    set_export_status: (state: import("./types.js").NonHistoricalState) => (status: ExportStatus) => void;
    set_fps: (state: import("./types.js").NonHistoricalState) => (fps: number) => void;
    set_log: (state: import("./types.js").NonHistoricalState) => (log: string) => void;
    set_selected_effect: (state: import("./types.js").NonHistoricalState) => (effect: AnyEffect | null) => void;
    set_project_resolution: (state: import("./types.js").NonHistoricalState) => (width: number, height: number) => void;
    update_transition: (state: import("./types.js").NonHistoricalState) => (transitionId: string) => void;
};
export declare const historical: {
    toggle_track_muted: (state: import("./types.js").HistoricalState) => (trackId: string) => void;
    toggle_track_visibility: (state: import("./types.js").HistoricalState) => (trackId: string) => void;
    toggle_track_locked: (state: import("./types.js").HistoricalState) => (trackId: string) => void;
    add_transition: (state: import("./types.js").HistoricalState) => (transition: Transition) => void;
    remove_transition: (state: import("./types.js").HistoricalState) => (id: string) => void;
    set_transition_duration: (state: import("./types.js").HistoricalState) => (duration: number, transitionId: string) => void;
    clear_transitions: (state: import("./types.js").HistoricalState) => () => void;
    clear_animations: (state: import("./types.js").HistoricalState) => () => void;
    set_animation_duration: (state: import("./types.js").HistoricalState) => (duration: number, { id }: VideoEffect | ImageEffect) => void;
    set_animations: (state: import("./types.js").HistoricalState) => (animations: Animation[]) => void;
    add_animation: (state: import("./types.js").HistoricalState) => (animation: Animation, animationFor: AnimationFor) => void;
    remove_animation: (state: import("./types.js").HistoricalState) => (effect: VideoEffect | ImageEffect, type: "in" | "out", animationFor: AnimationFor) => void;
    remove_filter: (state: import("./types.js").HistoricalState) => (effect: ImageEffect | VideoEffect, type: FilterType) => void;
    add_filter: (state: import("./types.js").HistoricalState) => (filter: Filter) => void;
    set_incoming_historical_state_webrtc: (state: import("./types.js").HistoricalState) => (historical: State) => void;
    set_project_id: (state: import("./types.js").HistoricalState) => (id: string) => void;
    set_effects: (state: import("./types.js").HistoricalState) => (effects: AnyEffect[]) => void;
    set_project_name: (state: import("./types.js").HistoricalState) => (value: string) => void;
    add_text_effect: (state: import("./types.js").HistoricalState) => (effect: TextEffect) => void;
    add_image_effect: (state: import("./types.js").HistoricalState) => (effect: ImageEffect) => void;
    add_video_effect: (state: import("./types.js").HistoricalState) => (effect: VideoEffect) => void;
    add_audio_effect: (state: import("./types.js").HistoricalState) => (effect: AudioEffect) => void;
    set_pivot: (state: import("./types.js").HistoricalState) => ({ id }: VideoEffect | ImageEffect | TextEffect, x: number, y: number) => void;
    set_text_fill: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, color: string, index: number) => void;
    move_text_fill_up: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, index: number) => void;
    move_text_fill_down: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, index: number) => void;
    set_text_font: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, font: Font) => void;
    set_font_size: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, size: number) => void;
    set_font_style: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, style: TextStyleFontStyle) => void;
    set_font_align: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, align: TextStyleAlign) => void;
    set_font_variant: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, variant: TextStyleFontVariant) => void;
    set_font_weight: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, weight: TextStyleFontWeight) => void;
    set_fill_gradient_type: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, type: TEXT_GRADIENT) => void;
    add_fill_gradient_stop: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect) => void;
    remove_fill_gradient_stop: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, index: number) => void;
    set_fill_gradient_stop: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, index: number, value: number) => void;
    set_text_rect: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, rect: EffectRect) => void;
    set_text_content: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, content: string) => void;
    add_text_fill: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect) => void;
    remove_text_fill: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, index: number) => void;
    set_stroke_color: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: string) => void;
    set_stroke_thickness: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_stroke_line_join: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: LineJoin) => void;
    set_stroke_miter_limit: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_text_baseline: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: TextStyleTextBaseline) => void;
    set_letter_spacing: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_drop_shadow_distance: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_drop_shadow_blur: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_drop_shadow_alpha: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_drop_shadow_angle: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_drop_shadow_color: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: ColorSource) => void;
    toggle_drop_shadow: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: boolean) => void;
    set_word_wrap: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: boolean) => void;
    set_break_words: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: boolean) => void;
    set_wrap_width: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_leading: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_line_height: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: number) => void;
    set_white_space: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect, value: TextStyleWhiteSpace) => void;
    set_effect_track: (state: import("./types.js").HistoricalState) => (effect: AnyEffect, track: number) => void;
    set_effect_duration: (state: import("./types.js").HistoricalState) => ({ id }: AnyEffect, duration: number) => void;
    set_effect_start_position: (state: import("./types.js").HistoricalState) => ({ id }: AnyEffect, x: number) => void;
    set_effect_start: (state: import("./types.js").HistoricalState) => ({ id }: AnyEffect, start: number) => void;
    set_effect_end: (state: import("./types.js").HistoricalState) => ({ id }: AnyEffect, end: number) => void;
    add_track: (state: import("./types.js").HistoricalState) => () => void;
    remove_track: (state: import("./types.js").HistoricalState) => (id: string) => void;
    remove_tracks: (state: import("./types.js").HistoricalState) => () => void;
    set_rotation: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect | ImageEffect | VideoEffect, rotation: number) => void;
    set_position_on_canvas: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect | ImageEffect | VideoEffect, x: number, y: number) => void;
    set_effect_width: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect | ImageEffect | VideoEffect, width: number) => void;
    set_effect_height: (state: import("./types.js").HistoricalState) => ({ id }: TextEffect | ImageEffect | VideoEffect, height: number) => void;
    remove_effect: (state: import("./types.js").HistoricalState) => ({ id }: AnyEffect) => void;
    set_effect_scale: (state: import("./types.js").HistoricalState) => (effect: TextEffect | ImageEffect | VideoEffect, scale: {
        x: number;
        y: number;
    }) => void;
    remove_all_effects: (state: import("./types.js").HistoricalState) => () => void;
};
export declare const historical_actions: HistoricalActionsWithBroadcast;
export declare const non_historical_actions: NonHistoricalActionsWithBroadcast;
export type Actions = HistoricalActions & NonHistoricalActions;
type HistoricalActions = ZipAction.Callable<typeof historical_actions>;
type NonHistoricalActions = ZipAction.Callable<typeof non_historical_actions>;
export {};
