import { Pojo, Nexus } from "@benev/slate";
import { Context, PanelSpec } from "@benev/construct/x/mini.js";
import { Media } from "./controllers/media/controller.js";
import { Timeline } from "./controllers/timeline/controller.js";
import { Shortcuts } from "./controllers/shortcuts/controller.js";
import { Compositor } from "./controllers/compositor/controller.js";
import { VideoExport } from "./controllers/video-export/controller.js";
import { HistoricalState, State } from "./types.js";
import { Collaboration } from "./controllers/collaboration/controller.js";
import { FFmpegHelper } from "./controllers/video-export/helpers/FFmpegHelper/helper.js";
import { StockLayouts } from "@benev/construct/x/context/controllers/layout/parts/utils/stock_layouts.js";
export interface MiniContextOptions {
    projectId: string;
    panels: Pojo<PanelSpec>;
    layouts: StockLayouts;
}
export declare const collaboration: Collaboration;
export declare class OmniContext extends Context {
    #private;
    get state(): State;
    get actions(): {
        toggle_track_muted: (trackId: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        toggle_track_visibility: (trackId: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        toggle_track_locked: (trackId: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_transition: (transition: import("./controllers/compositor/parts/transition-manager.js").Transition, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_transition: (id: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_transition_duration: (duration: number, transitionId: string, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        clear_transitions: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        clear_animations: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_animation_duration: (duration: number, innerArgs_1: import("./types.js").VideoEffect | import("./types.js").ImageEffect, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_animations: (animations: import("./controllers/compositor/parts/animation-manager.js").Animation[], innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_animation: (animation: import("./controllers/compositor/parts/animation-manager.js").Animation, animationFor: import("./controllers/compositor/parts/animation-manager.js").AnimationFor, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_animation: (effect: import("./types.js").VideoEffect | import("./types.js").ImageEffect, type: "in" | "out", animationFor: import("./controllers/compositor/parts/animation-manager.js").AnimationFor, innerArgs_3?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_filter: (effect: import("./types.js").VideoEffect | import("./types.js").ImageEffect, type: import("./controllers/compositor/parts/filter-manager.js").FilterType, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_filter: (filter: import("./controllers/compositor/parts/filter-manager.js").Filter, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_incoming_historical_state_webrtc: (historical: State, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_project_id: (id: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effects: (effects: import("./types.js").AnyEffect[], innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_project_name: (value: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_text_effect: (effect: import("./types.js").TextEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_image_effect: (effect: import("./types.js").ImageEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_video_effect: (effect: import("./types.js").VideoEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_audio_effect: (effect: import("./types.js").AudioEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_pivot: (innerArgs_0: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, x: number, y: number, innerArgs_3?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_text_fill: (innerArgs_0: import("./types.js").TextEffect, color: string, index: number, innerArgs_3?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        move_text_fill_up: (innerArgs_0: import("./types.js").TextEffect, index: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        move_text_fill_down: (innerArgs_0: import("./types.js").TextEffect, index: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_text_font: (innerArgs_0: import("./types.js").TextEffect, font: string, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_font_size: (innerArgs_0: import("./types.js").TextEffect, size: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_font_style: (innerArgs_0: import("./types.js").TextEffect, style: import("pixi.js").TextStyleFontStyle, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_font_align: (innerArgs_0: import("./types.js").TextEffect, align: import("pixi.js").TextStyleAlign, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_font_variant: (innerArgs_0: import("./types.js").TextEffect, variant: import("pixi.js").TextStyleFontVariant, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_font_weight: (innerArgs_0: import("./types.js").TextEffect, weight: import("pixi.js").TextStyleFontWeight, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_fill_gradient_type: (innerArgs_0: import("./types.js").TextEffect, type: import("pixi.js").TEXT_GRADIENT, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_fill_gradient_stop: (innerArgs_0: import("./types.js").TextEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_fill_gradient_stop: (innerArgs_0: import("./types.js").TextEffect, index: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_fill_gradient_stop: (innerArgs_0: import("./types.js").TextEffect, index: number, value: number, innerArgs_3?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_text_rect: (innerArgs_0: import("./types.js").TextEffect, rect: import("./types.js").EffectRect, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_text_content: (innerArgs_0: import("./types.js").TextEffect, content: string, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_text_fill: (innerArgs_0: import("./types.js").TextEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_text_fill: (innerArgs_0: import("./types.js").TextEffect, index: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_stroke_color: (innerArgs_0: import("./types.js").TextEffect, value: string, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_stroke_thickness: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_stroke_line_join: (innerArgs_0: import("./types.js").TextEffect, value: import("./pixi.mjs.js").LineJoin, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_stroke_miter_limit: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_text_baseline: (innerArgs_0: import("./types.js").TextEffect, value: import("pixi.js").TextStyleTextBaseline, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_letter_spacing: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_drop_shadow_distance: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_drop_shadow_blur: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_drop_shadow_alpha: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_drop_shadow_angle: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_drop_shadow_color: (innerArgs_0: import("./types.js").TextEffect, value: import("pixi.js").ColorSource, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        toggle_drop_shadow: (innerArgs_0: import("./types.js").TextEffect, value: boolean, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_word_wrap: (innerArgs_0: import("./types.js").TextEffect, value: boolean, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_break_words: (innerArgs_0: import("./types.js").TextEffect, value: boolean, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_wrap_width: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_leading: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_line_height: (innerArgs_0: import("./types.js").TextEffect, value: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_white_space: (innerArgs_0: import("./types.js").TextEffect, value: import("pixi.js").TextStyleWhiteSpace, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_track: (effect: import("./types.js").AnyEffect, track: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_duration: (innerArgs_0: import("./types.js").AnyEffect, duration: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_start_position: (innerArgs_0: import("./types.js").AnyEffect, x: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_start: (innerArgs_0: import("./types.js").AnyEffect, start: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_end: (innerArgs_0: import("./types.js").AnyEffect, end: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        add_track: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_track: (id: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_tracks: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_rotation: (innerArgs_0: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, rotation: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_position_on_canvas: (innerArgs_0: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, x: number, y: number, innerArgs_3?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_width: (innerArgs_0: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, width: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_height: (innerArgs_0: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, height: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_effect: (innerArgs_0: import("./types.js").AnyEffect, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_effect_scale: (effect: import("./types.js").VideoEffect | import("./types.js").TextEffect | import("./types.js").ImageEffect, scale: {
            x: number;
            y: number;
        }, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        remove_all_effects: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        clear_project: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_incoming_non_historical_state_webrtc: (historical: State, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_standard: (standard: import("./types.js").Standard, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_aspect_ratio: (aspectRatio: import("./types.js").AspectRatio, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_bitrate: (value: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        zoom_in: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        zoom_out: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_timecode: (timecode: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        increase_timecode: (by_milliseconds: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_is_playing: (is_playing: boolean, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        toggle_is_playing: (innerArgs_0?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_is_exporting: (is_exporting: boolean, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_export_progress: (progress: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_timebase: (timebase: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_export_status: (status: import("./types.js").ExportStatus, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_fps: (fps: number, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_log: (log: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_selected_effect: (effect: import("./types.js").AnyEffect | null, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        set_project_resolution: (width: number, height: number, innerArgs_2?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
        update_transition: (transitionId: string, innerArgs_1?: import("../utils/with-broadcast.js").BroadcastOptions | undefined) => void;
    };
    undo(): void;
    redo(): void;
    clear_project(omit?: boolean): void;
    get history(): import("@benev/slate/x/watch/framework/utils/annals.js").Annals<HistoricalState>;
    helpers: {
        ffmpeg: FFmpegHelper;
    };
    is_webcodecs_supported: import("@benev/slate").OpSignal<any>;
    controllers: {
        timeline: Timeline;
        compositor: Compositor;
        media: Media;
        video_export: VideoExport;
        shortcuts: Shortcuts;
        collaboration: Collaboration;
    };
    constructor(options: MiniContextOptions);
}
export declare const omnislate: Nexus<OmniContext>;
export declare const shadow_component: (renderer: import("@benev/slate").ShadowComponentRenderer<OmniContext>) => typeof import("@benev/slate").GoldElement, shadow_view: <P extends any[]>(renderer: import("@benev/slate").ShadowViewRenderer<OmniContext, P>) => (props: P, meta?: Partial<{
    content: import("@benev/slate").TemplateResult<1 | 2>;
    auto_exportparts: boolean;
    attrs: import("@benev/slate").ShadowAttrs;
}> | undefined) => import("@benev/slate").DirectiveResult<any>, light_view: <P extends any[]>(renderer: import("@benev/slate").LightViewRenderer<OmniContext, P>) => (...props: P) => import("@benev/slate").DirectiveResult<any>, light_component: (renderer: import("@benev/slate").LightComponentRenderer<OmniContext>) => new () => {
    [x: string]: any;
    "__#36@#use": import("@benev/slate").UseLightComponent<OmniContext>;
    "__#36@#rend": () => void | import("@benev/slate").TemplateResult<1 | 2>;
    "__#36@#reactivity"?: import("@benev/slate/x/nexus/parts/setup_reactivity.js").Reactivity<[]> | undefined;
    render(): void | import("@benev/slate").TemplateResult<1 | 2> | undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    "__#27@#init"?: {
        promise: Promise<void>;
        resolve: (value: void) => void;
        reject: (reason: any) => void;
    } | undefined;
    "__#27@#wait": Promise<void>;
    init(): void;
    readonly updateComplete: Promise<boolean>;
    "__#27@#render_debounced": import("@benev/slate/x/tools/debounce/types.js").DebounceReturn<() => void>;
    requestUpdate(): Promise<void>;
    "__#25@#setups": Set<() => () => void>;
    "__#25@#setdowns": Set<() => void>;
    register_setup(setup: () => () => void): void;
    setup(): () => void;
    accessKey: string;
    readonly accessKeyLabel: string;
    autocapitalize: string;
    dir: string;
    draggable: boolean;
    hidden: boolean;
    inert: boolean;
    innerText: string;
    lang: string;
    readonly offsetHeight: number;
    readonly offsetLeft: number;
    readonly offsetParent: Element | null;
    readonly offsetTop: number;
    readonly offsetWidth: number;
    outerText: string;
    popover: string | null;
    spellcheck: boolean;
    title: string;
    translate: boolean;
    attachInternals(): ElementInternals;
    click(): void;
    hidePopover(): void;
    showPopover(): void;
    togglePopover(force?: boolean | undefined): boolean;
    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions | undefined): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void;
    removeEventListener<K_1 extends keyof HTMLElementEventMap>(type: K_1, listener: (this: HTMLElement, ev: HTMLElementEventMap[K_1]) => any, options?: boolean | EventListenerOptions | undefined): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions | undefined): void;
    readonly attributes: NamedNodeMap;
    readonly classList: DOMTokenList;
    className: string;
    readonly clientHeight: number;
    readonly clientLeft: number;
    readonly clientTop: number;
    readonly clientWidth: number;
    id: string;
    readonly localName: string;
    readonly namespaceURI: string | null;
    onfullscreenchange: ((this: Element, ev: Event) => any) | null;
    onfullscreenerror: ((this: Element, ev: Event) => any) | null;
    outerHTML: string;
    readonly ownerDocument: Document;
    readonly part: DOMTokenList;
    readonly prefix: string | null;
    readonly scrollHeight: number;
    scrollLeft: number;
    scrollTop: number;
    readonly scrollWidth: number;
    readonly shadowRoot: ShadowRoot | null;
    slot: string;
    readonly tagName: string;
    attachShadow(init: ShadowRootInit): ShadowRoot;
    checkVisibility(options?: CheckVisibilityOptions | undefined): boolean;
    closest<K_2 extends keyof HTMLElementTagNameMap>(selector: K_2): HTMLElementTagNameMap[K_2] | null;
    closest<K_3 extends keyof SVGElementTagNameMap>(selector: K_3): SVGElementTagNameMap[K_3] | null;
    closest<K_4 extends keyof MathMLElementTagNameMap>(selector: K_4): MathMLElementTagNameMap[K_4] | null;
    closest<E extends Element = Element>(selectors: string): E | null;
    computedStyleMap(): StylePropertyMapReadOnly;
    getAttribute(qualifiedName: string): string | null;
    getAttributeNS(namespace: string | null, localName: string): string | null;
    getAttributeNames(): string[];
    getAttributeNode(qualifiedName: string): Attr | null;
    getAttributeNodeNS(namespace: string | null, localName: string): Attr | null;
    getBoundingClientRect(): DOMRect;
    getClientRects(): DOMRectList;
    getElementsByClassName(classNames: string): HTMLCollectionOf<Element>;
    getElementsByTagName<K_5 extends keyof HTMLElementTagNameMap>(qualifiedName: K_5): HTMLCollectionOf<HTMLElementTagNameMap[K_5]>;
    getElementsByTagName<K_6 extends keyof SVGElementTagNameMap>(qualifiedName: K_6): HTMLCollectionOf<SVGElementTagNameMap[K_6]>;
    getElementsByTagName<K_7 extends keyof MathMLElementTagNameMap>(qualifiedName: K_7): HTMLCollectionOf<MathMLElementTagNameMap[K_7]>;
    getElementsByTagName<K_8 extends keyof HTMLElementDeprecatedTagNameMap>(qualifiedName: K_8): HTMLCollectionOf<HTMLElementDeprecatedTagNameMap[K_8]>;
    getElementsByTagName(qualifiedName: string): HTMLCollectionOf<Element>;
    getElementsByTagNameNS(namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
    getElementsByTagNameNS(namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
    getElementsByTagNameNS(namespaceURI: "http://www.w3.org/1998/Math/MathML", localName: string): HTMLCollectionOf<MathMLElement>;
    getElementsByTagNameNS(namespace: string | null, localName: string): HTMLCollectionOf<Element>;
    hasAttribute(qualifiedName: string): boolean;
    hasAttributeNS(namespace: string | null, localName: string): boolean;
    hasAttributes(): boolean;
    hasPointerCapture(pointerId: number): boolean;
    insertAdjacentElement(where: InsertPosition, element: Element): Element | null;
    insertAdjacentHTML(position: InsertPosition, text: string): void;
    insertAdjacentText(where: InsertPosition, data: string): void;
    matches(selectors: string): boolean;
    releasePointerCapture(pointerId: number): void;
    removeAttribute(qualifiedName: string): void;
    removeAttributeNS(namespace: string | null, localName: string): void;
    removeAttributeNode(attr: Attr): Attr;
    requestFullscreen(options?: FullscreenOptions | undefined): Promise<void>;
    requestPointerLock(): void;
    scroll(options?: ScrollToOptions | undefined): void;
    scroll(x: number, y: number): void;
    scrollBy(options?: ScrollToOptions | undefined): void;
    scrollBy(x: number, y: number): void;
    scrollIntoView(arg?: boolean | ScrollIntoViewOptions | undefined): void;
    scrollTo(options?: ScrollToOptions | undefined): void;
    scrollTo(x: number, y: number): void;
    setAttribute(qualifiedName: string, value: string): void;
    setAttributeNS(namespace: string | null, qualifiedName: string, value: string): void;
    setAttributeNode(attr: Attr): Attr | null;
    setAttributeNodeNS(attr: Attr): Attr | null;
    setPointerCapture(pointerId: number): void;
    toggleAttribute(qualifiedName: string, force?: boolean | undefined): boolean;
    webkitMatchesSelector(selectors: string): boolean;
    readonly baseURI: string;
    readonly childNodes: NodeListOf<ChildNode>;
    readonly firstChild: ChildNode | null;
    readonly isConnected: boolean;
    readonly lastChild: ChildNode | null;
    readonly nextSibling: ChildNode | null;
    readonly nodeName: string;
    readonly nodeType: number;
    nodeValue: string | null;
    readonly parentElement: HTMLElement | null;
    readonly parentNode: ParentNode | null;
    readonly previousSibling: ChildNode | null;
    textContent: string | null;
    appendChild<T extends Node>(node: T): T;
    cloneNode(deep?: boolean | undefined): Node;
    compareDocumentPosition(other: Node): number;
    contains(other: Node | null): boolean;
    getRootNode(options?: GetRootNodeOptions | undefined): Node;
    hasChildNodes(): boolean;
    insertBefore<T_1 extends Node>(node: T_1, child: Node | null): T_1;
    isDefaultNamespace(namespace: string | null): boolean;
    isEqualNode(otherNode: Node | null): boolean;
    isSameNode(otherNode: Node | null): boolean;
    lookupNamespaceURI(prefix: string | null): string | null;
    lookupPrefix(namespace: string | null): string | null;
    normalize(): void;
    removeChild<T_2 extends Node>(child: T_2): T_2;
    replaceChild<T_3 extends Node>(node: Node, child: T_3): T_3;
    readonly ELEMENT_NODE: 1;
    readonly ATTRIBUTE_NODE: 2;
    readonly TEXT_NODE: 3;
    readonly CDATA_SECTION_NODE: 4;
    readonly ENTITY_REFERENCE_NODE: 5;
    readonly ENTITY_NODE: 6;
    readonly PROCESSING_INSTRUCTION_NODE: 7;
    readonly COMMENT_NODE: 8;
    readonly DOCUMENT_NODE: 9;
    readonly DOCUMENT_TYPE_NODE: 10;
    readonly DOCUMENT_FRAGMENT_NODE: 11;
    readonly NOTATION_NODE: 12;
    readonly DOCUMENT_POSITION_DISCONNECTED: 1;
    readonly DOCUMENT_POSITION_PRECEDING: 2;
    readonly DOCUMENT_POSITION_FOLLOWING: 4;
    readonly DOCUMENT_POSITION_CONTAINS: 8;
    readonly DOCUMENT_POSITION_CONTAINED_BY: 16;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32;
    dispatchEvent(event: Event): boolean;
    ariaAtomic: string | null;
    ariaAutoComplete: string | null;
    ariaBusy: string | null;
    ariaChecked: string | null;
    ariaColCount: string | null;
    ariaColIndex: string | null;
    ariaColSpan: string | null;
    ariaCurrent: string | null;
    ariaDescription: string | null;
    ariaDisabled: string | null;
    ariaExpanded: string | null;
    ariaHasPopup: string | null;
    ariaHidden: string | null;
    ariaInvalid: string | null;
    ariaKeyShortcuts: string | null;
    ariaLabel: string | null;
    ariaLevel: string | null;
    ariaLive: string | null;
    ariaModal: string | null;
    ariaMultiLine: string | null;
    ariaMultiSelectable: string | null;
    ariaOrientation: string | null;
    ariaPlaceholder: string | null;
    ariaPosInSet: string | null;
    ariaPressed: string | null;
    ariaReadOnly: string | null;
    ariaRequired: string | null;
    ariaRoleDescription: string | null;
    ariaRowCount: string | null;
    ariaRowIndex: string | null;
    ariaRowSpan: string | null;
    ariaSelected: string | null;
    ariaSetSize: string | null;
    ariaSort: string | null;
    ariaValueMax: string | null;
    ariaValueMin: string | null;
    ariaValueNow: string | null;
    ariaValueText: string | null;
    role: string | null;
    animate(keyframes: PropertyIndexedKeyframes | Keyframe[] | null, options?: number | KeyframeAnimationOptions | undefined): Animation;
    getAnimations(options?: GetAnimationsOptions | undefined): Animation[];
    after(...nodes: (string | Node)[]): void;
    before(...nodes: (string | Node)[]): void;
    remove(): void;
    replaceWith(...nodes: (string | Node)[]): void;
    innerHTML: string;
    readonly nextElementSibling: Element | null;
    readonly previousElementSibling: Element | null;
    readonly childElementCount: number;
    readonly children: HTMLCollection;
    readonly firstElementChild: Element | null;
    readonly lastElementChild: Element | null;
    append(...nodes: (string | Node)[]): void;
    prepend(...nodes: (string | Node)[]): void;
    querySelector<K_9 extends keyof HTMLElementTagNameMap>(selectors: K_9): HTMLElementTagNameMap[K_9] | null;
    querySelector<K_10 extends keyof SVGElementTagNameMap>(selectors: K_10): SVGElementTagNameMap[K_10] | null;
    querySelector<K_11 extends keyof MathMLElementTagNameMap>(selectors: K_11): MathMLElementTagNameMap[K_11] | null;
    querySelector<K_12 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_12): HTMLElementDeprecatedTagNameMap[K_12] | null;
    querySelector<E_1 extends Element = Element>(selectors: string): E_1 | null;
    querySelectorAll<K_13 extends keyof HTMLElementTagNameMap>(selectors: K_13): NodeListOf<HTMLElementTagNameMap[K_13]>;
    querySelectorAll<K_14 extends keyof SVGElementTagNameMap>(selectors: K_14): NodeListOf<SVGElementTagNameMap[K_14]>;
    querySelectorAll<K_15 extends keyof MathMLElementTagNameMap>(selectors: K_15): NodeListOf<MathMLElementTagNameMap[K_15]>;
    querySelectorAll<K_16 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_16): NodeListOf<HTMLElementDeprecatedTagNameMap[K_16]>;
    querySelectorAll<E_2 extends Element = Element>(selectors: string): NodeListOf<E_2>;
    replaceChildren(...nodes: (string | Node)[]): void;
    readonly assignedSlot: HTMLSlotElement | null;
    readonly attributeStyleMap: StylePropertyMap;
    readonly style: CSSStyleDeclaration;
    contentEditable: string;
    enterKeyHint: string;
    inputMode: string;
    readonly isContentEditable: boolean;
    onabort: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null;
    onanimationcancel: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null;
    onanimationend: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null;
    onanimationiteration: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null;
    onanimationstart: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null;
    onauxclick: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onbeforeinput: ((this: GlobalEventHandlers, ev: InputEvent) => any) | null;
    onbeforetoggle: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onblur: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null;
    oncancel: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    oncanplay: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    oncanplaythrough: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onchange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onclick: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onclose: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    oncontextmenu: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    oncopy: ((this: GlobalEventHandlers, ev: ClipboardEvent) => any) | null;
    oncuechange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    oncut: ((this: GlobalEventHandlers, ev: ClipboardEvent) => any) | null;
    ondblclick: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    ondrag: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondragend: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondragenter: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondragleave: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondragover: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondragstart: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondrop: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null;
    ondurationchange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onemptied: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onended: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onerror: OnErrorEventHandler;
    onfocus: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null;
    onformdata: ((this: GlobalEventHandlers, ev: FormDataEvent) => any) | null;
    ongotpointercapture: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    oninput: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    oninvalid: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onkeydown: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null;
    onkeypress: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null;
    onkeyup: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null;
    onload: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onloadeddata: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onloadedmetadata: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onloadstart: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onlostpointercapture: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onmousedown: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmouseenter: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmouseleave: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmousemove: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmouseout: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmouseover: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onmouseup: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null;
    onpaste: ((this: GlobalEventHandlers, ev: ClipboardEvent) => any) | null;
    onpause: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onplay: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onplaying: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onpointercancel: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerdown: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerenter: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerleave: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointermove: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerout: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerover: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onpointerup: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null;
    onprogress: ((this: GlobalEventHandlers, ev: ProgressEvent<EventTarget>) => any) | null;
    onratechange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onreset: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onresize: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null;
    onscroll: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onscrollend: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onsecuritypolicyviolation: ((this: GlobalEventHandlers, ev: SecurityPolicyViolationEvent) => any) | null;
    onseeked: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onseeking: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onselect: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onselectionchange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onselectstart: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onslotchange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onstalled: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onsubmit: ((this: GlobalEventHandlers, ev: SubmitEvent) => any) | null;
    onsuspend: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    ontimeupdate: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    ontoggle: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    ontouchcancel?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchend?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchmove?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchstart?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontransitioncancel: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null;
    ontransitionend: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null;
    ontransitionrun: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null;
    ontransitionstart: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null;
    onvolumechange: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwaiting: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwebkitanimationend: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwebkitanimationiteration: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwebkitanimationstart: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwebkittransitionend: ((this: GlobalEventHandlers, ev: Event) => any) | null;
    onwheel: ((this: GlobalEventHandlers, ev: WheelEvent) => any) | null;
    autofocus: boolean;
    readonly dataset: DOMStringMap;
    nonce?: string | undefined;
    tabIndex: number;
    blur(): void;
    focus(options?: FocusOptions | undefined): void;
};
